### ISSUE TITLE
Accepting more users?

### ISSUE THREAD

**Issue by kaushalmodi** [voxpelli/webpage-webmentions#50]
Hello, 

I was reading this post, and was trying to set up receiving of webmentions on my site scripter.co too..

But looks like this service is maxed out at 150 users?

Is there a plan to allow more users?

Thanks.

**Comment by voxpelli** [comment]
Yes there is, I just have to fix a memory issue first and I haven’t had time yet :/

**Comment by voxpelli** [comment]
The limit is now raised to 160 so that a few more of you can get in while I continue to try and find time to fix the memory "issue"

(The issue is that there are some methods that lack pagination due to me being lazy and not implementing it initially due to it not being needed, but some users now have quite a few posts and when loading all those posts from the database, the service at times runs out of memory and is restarted by Heroku)
